---
title: "Exceptions"
author: "Kamil FoltyÅ„ski"
date: "03/04/2019"
output:
  html_document:
    fig_caption: yes
    keep_md: no
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
runtime: shiny
---

```{r, echo=FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = ">")
```

# What is exception?

> Definition: An exception is an event, which occurs during the execution of a program, that disrupts the normal flow of the program's instructions.

# Why should we care?

Let's see example first:

```{r,error=TRUE}
library(dplyr)
# prepare test data
df <- mtcars
df$car <- row.names(mtcars)
row.names(df) <- c()
df_hp <- df[, c("car", "hp")]
df <- df[!names(df) %in% "hp"]
df1 <- df[1:16, ]
df2 <- df[17:nrow(df), ]
df.list <- list(df1, df2)

head(df1, 2)

head(df2, 2)

head(df_hp, 2)

# declare fun to convert get N top row from data frames in argument list
subsetTopNAndJoinDataTOresult <- function(list_data, data2join, key, top_n_rows = 3) {
  
  subsetTopN <- function(input, n) {
    lapply(input, function(x) head(x, n))
  }
  
  result <- subsetTopN(list_data, top_n_rows)
  
  # join horse power to each element of list
  lapply(result, function(x) {
    x %>% left_join(data2join, by = key)
  })
}

result <- subsetTopNAndJoinDataTOresult(list_data = df.list, data2join = df_hp, key = "car")
result # everything went well :)

# ...but imagine that list_data argument is not even a list - it is just ONE data frame
result2 <- subsetTopNAndJoinDataTOresult(list_data = df1, data2join = df_hp, key = "hp")
```

The problem is that `df` is both `data.frame` and `list`:

```{r}
df <- mtcars
is.data.frame(df)
is.list(df)
```

and `lapply` function's `X` argument is coerced by `base::as.list`, so output from `subsetTopN` is
list and is being joined to `data.frame` named `df_hp`:

```{r}
lapply(mtcars[1:3], function(x) print(head(x, 2)))
```

# Exception handling

The above code's problem is that it neither verifies any of input data nor edge cases. 
What can we do is to try to **handle exception**. For example:

```{r,error=TRUE}
library(dplyr)
# prepare data
df <- mtcars
df$car <- row.names(mtcars)
row.names(df) <- c()
df_hp <- df[, c("car", "hp")]
df <- df[!names(df) %in% "hp"]
df1 <- df[1:16, ]
df2 <- df[17:nrow(df), ]
df.list <- list(df1, df2)

subsetTopNAndJoinDataTOresult <- function(list_data, data2join, key, top_n_rows = 3) {
  
  subsetTopN <- function(input, n) {
    lapply(input, function(x) {
      
      if (!is.data.frame(x))
        stop(sprintf("'x' argument is not data.frame class but %s", class(x)))
      
        head(x, n)
    })
  }
  
  result <- subsetTopN(list_data, top_n_rows)
  
  # join horse power to each element of list
  lapply(result, function(x) {
    x %>% left_join(data2join, by = key)
  })
}

result <- subsetTopNAndJoinDataTOresult(list_data = df1, data2join = df_hp, key = "car")

```

There are also many ways to handle exceptions:

1. are all needed arguments provided?
2. are variables and functions's arguments the expected type/class?
3. if variables' types match expected, then if variables provide enough informations? e.g.:

```{r}
df <- data.frame()
is.data.frame(df)
nrow(df) > 0
```

# Answers

But initial question was _**why should we care about exceptions?**_, so let's try to answer:

1. We have **more control over the code** behaviour. We can notice problem quicker, for example
by verifying quality of function's arguments in first lines of its body
2. Handling exceptions **saves time on debugging**: 

Error message: `'x' argument is not data.frame class but numeric**_`

is more understandable than

`Error in UseMethod("left_join"): niestosowalna metoda dla 'left_join' zastosowana do obiektu klasy "c('double', 'numeric')"`, 

isn't it? :)


# Testing exceptions

Exceptions and error messages can also be tested. 
And again it is about code behaviour control. By testing exceptions we expect that code will throw
**specific error** in specific case. 
For example, we can expect that on error further code execution will stop and won't insert do SQL database
data frame full of thousands of `NA`s :)

Example:

```{r,error=TRUE}
testthat::context("subsetTopNAndJoinDataTOresult")
testthat::test_that("throws error if input is 1 data frame", {
  
  df <- mtcars
  df$car <- row.names(mtcars)
  row.names(df) <- c()
  df_hp <- df[, c("car", "hp")]
  df <- df[!names(df) %in% "hp"]
  
  testthat::expect_error(
    unitTestsWorkshopPackage::subsetTopNAndJoinDataTOresult(list_data = df, data2join = df_hp, key = "car"),
    regexp = ".*'x' argument is not data\\.frame class but numeric.*"
  )
})
```


# Practice

## Task 1

Suggest validation of `unitTestsWorkshopPackage::subsetTopNAndJoinDataTOresult` arguments

## Task 2

Handle and test exceptions when:

* `data2join` have 0 rows
* `list_data` has 0 length

## Task 3

Write unit test for `unitTestsWorkshopPackage::subsetTopNAndJoinDataTOresult`




